FROM python:3.9-alpine

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY targets/test_server.py /app/test_server.py

EXPOSE 80

RUN pip install gunicorn
CMD [ "gunicorn", "--workers", "4", "--bind", "0.0.0.0:80","test_server:app" ]